GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/15

###
POST http://localhost:3001/api/persons
content-type: application/json

{ 
    "name": "Yisaccddd Aberham", 
    "number": "040-123456"
}